name: tadwir_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # Google Generative AI
  google_generative_ai: ^0.2.0

  # Camera and Image Picker
  image_picker: ^1.0.4
  camera: ^0.10.5+5

  # State Management
  provider: ^6.0.5

  # Other
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
